# Generated by Django 3.2.8 on 2023-04-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('begin_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2019)),
                ('half', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
