# Generated by Django 3.2.8 on 2023-04-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230405_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default='null', max_length=50, unique=True)),
                ('college', models.CharField(default='', max_length=30)),
                ('grade', models.IntegerField(default=2019)),
                ('major', models.CharField(default='', max_length=50)),
                ('class_number', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=30)),
                ('sex', models.IntegerField(default=0)),
                ('brithday', models.IntegerField(default=0)),
                ('source', models.CharField(default='', max_length=30)),
                ('address', models.TextField(default='')),
                ('idcard', models.CharField(default='', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, default=160, max_digits=6, null=True)),
                ('weight', models.DecimalField(decimal_places=2, default=50, max_digits=6, null=True)),
                ('pulmonary', models.IntegerField(default=2000, null=True)),
                ('run50', models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True)),
                ('jump', models.DecimalField(decimal_places=2, default=180, max_digits=6, null=True)),
                ('flexion', models.DecimalField(decimal_places=2, default=10, max_digits=6, null=True)),
                ('run800', models.IntegerField(default=0, null=True)),
                ('run1000', models.IntegerField(default=0, null=True)),
                ('adbominal_curl', models.IntegerField(default=30, null=True)),
                ('pull_up', models.IntegerField(default=5, null=True)),
                ('left_eye', models.DecimalField(decimal_places=2, default=5, max_digits=6, null=True)),
                ('right_eye', models.DecimalField(decimal_places=2, default=5, max_digits=6, null=True)),
                ('bmi_score', models.IntegerField(default=65, null=True)),
                ('pulmonary_score', models.IntegerField(default=65, null=True)),
                ('run50_score', models.IntegerField(default=65, null=True)),
                ('jump_score', models.IntegerField(default=65, null=True)),
                ('flexion_score', models.IntegerField(default=65, null=True)),
                ('runlong_score', models.IntegerField(default=65, null=True)),
                ('curlorup_score', models.IntegerField(default=65, null=True)),
                ('end_score', models.IntegerField(default=65, null=True)),
                ('remark', models.TextField(default='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studentinfomation')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
    ]
