# Generated by Django 3.2.8 on 2023-04-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tempfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField(default='未知')),
                ('college', models.TextField(default='未知')),
                ('major', models.TextField(default='未知')),
                ('class_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.TextField(default='low')),
                ('bmi', models.TextField(default='[]')),
                ('pulmonary', models.TextField(default='[]')),
                ('run50', models.TextField(default='[]')),
                ('jump', models.TextField(default='[]')),
                ('flexion', models.TextField(default='[]')),
                ('run800', models.TextField(default='[]')),
                ('adbominal_curl', models.TextField(default='[]')),
                ('pull_up', models.TextField(default='[]')),
                ('run1000', models.TextField(default='[]')),
                ('end_score', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default='null', max_length=50, unique=True)),
                ('name', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='studentinfomation',
            name='nation',
            field=models.CharField(default='', max_length=19),
        ),
    ]
