# Generated by Django 3.2.8 on 2023-04-29 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_class_number_studentinfomation_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.teacherinfomation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfomation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfomation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
    ]
