# Generated by Django 3.2.8 on 2023-04-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230430_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='adbominal_curl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='bmi_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='curlorup_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='flexion',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='flexion_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='jump',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='jump_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='left_eye',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='pull_up',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='pulmonary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='pulmonary_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='right_eye',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='run1000',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='run50',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='run50_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='run800',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='runlong_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
