# Generated by Django 3.2.8 on 2023-05-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230505_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='flexion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='jump',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='left_eye',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='right_eye',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='run50',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
